//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

 public abstract class ApplicationService : IApplicationService
 {
   protected readonly IRepository<Domain.d_qyjjlx> _d_qyjjlxRepository;
   protected readonly IRepository<Domain.g_BusinessLog> _g_BusinessLogRepository;
   protected readonly IRepository<Domain.g_statetransferrule> _g_statetransferruleRepository;
   protected readonly IRepository<Domain.gczj_code> _gczj_codeRepository;
   protected readonly IRepository<Domain.gczj_glyh_dq> _gczj_glyh_dqRepository;
   protected readonly IRepository<Domain.gczj_jgjs_dwgcxxb> _gczj_jgjs_dwgcxxbRepository;
   protected readonly IRepository<Domain.gczj_jgjsglb> _gczj_jgjsglbRepository;
   protected readonly IRepository<Domain.gczj_jjscglb> _gczj_jjscglbRepository;
   protected readonly IRepository<Domain.gczj_sgcsfhdglb> _gczj_sgcsfhdglbRepository;
   protected readonly IRepository<Domain.gczj_xmxx> _gczj_xmxxRepository;
   protected readonly IRepository<Domain.gczj_zbkzjba_xmz> _gczj_zbkzjba_xmzRepository;
   protected readonly IRepository<Domain.gczj_zbkzjbaglb> _gczj_zbkzjbaglbRepository;
   protected readonly IRepository<Domain.gczj_zbkzjbaglb_20140709> _gczj_zbkzjbaglb_20140709Repository;
   protected readonly IRepository<Domain.gczj_zbkzjbaglb_20150610> _gczj_zbkzjbaglb_20150610Repository;
   protected readonly IRepository<Domain.jsdw_jbqkb> _jsdw_jbqkbRepository;
   protected readonly IRepository<Domain.org_business> _org_businessRepository;
   protected readonly IRepository<Domain.sgtyk_gljsryqkb> _sgtyk_gljsryqkbRepository;
   protected readonly IRepository<Domain.sgtyk_qyjbqkb> _sgtyk_qyjbqkbRepository;
   protected readonly IRepository<Domain.UEPP_Code> _UEPP_CodeRepository;
   protected readonly IRepository<Domain.UEPP_Qycsyw> _UEPP_QycsywRepository;
   protected readonly IRepository<Domain.UEPP_Qyjbxx> _UEPP_QyjbxxRepository;
   protected readonly IRepository<Domain.UEPP_QyRy> _UEPP_QyRyRepository;
   protected readonly IRepository<Domain.UEPP_Ryjbxx> _UEPP_RyjbxxRepository;
   protected readonly IRepository<Domain.UserInfo> _UserInfoRepository;
   protected readonly IRepository<Domain.wdecolinf> _wdecolinfRepository;
   protected readonly IRepository<Domain.wdetabinf> _wdetabinfRepository;

protected readonly IDbContext _dbcontext;
protected readonly IRedis _redishelper;
protected readonly IEventPublisher _eventPublisher;
protected readonly ILogger _logger;

 public ApplicationService(
    IRepository<Domain.d_qyjjlx> d_qyjjlxRepository,
   IRepository<Domain.g_BusinessLog> g_BusinessLogRepository,
   IRepository<Domain.g_statetransferrule> g_statetransferruleRepository,
   IRepository<Domain.gczj_code> gczj_codeRepository,
   IRepository<Domain.gczj_glyh_dq> gczj_glyh_dqRepository,
   IRepository<Domain.gczj_jgjs_dwgcxxb> gczj_jgjs_dwgcxxbRepository,
   IRepository<Domain.gczj_jgjsglb> gczj_jgjsglbRepository,
   IRepository<Domain.gczj_jjscglb> gczj_jjscglbRepository,
   IRepository<Domain.gczj_sgcsfhdglb> gczj_sgcsfhdglbRepository,
   IRepository<Domain.gczj_xmxx> gczj_xmxxRepository,
   IRepository<Domain.gczj_zbkzjba_xmz> gczj_zbkzjba_xmzRepository,
   IRepository<Domain.gczj_zbkzjbaglb> gczj_zbkzjbaglbRepository,
   IRepository<Domain.gczj_zbkzjbaglb_20140709> gczj_zbkzjbaglb_20140709Repository,
   IRepository<Domain.gczj_zbkzjbaglb_20150610> gczj_zbkzjbaglb_20150610Repository,
   IRepository<Domain.jsdw_jbqkb> jsdw_jbqkbRepository,
   IRepository<Domain.org_business> org_businessRepository,
   IRepository<Domain.sgtyk_gljsryqkb> sgtyk_gljsryqkbRepository,
   IRepository<Domain.sgtyk_qyjbqkb> sgtyk_qyjbqkbRepository,
   IRepository<Domain.UEPP_Code> UEPP_CodeRepository,
   IRepository<Domain.UEPP_Qycsyw> UEPP_QycsywRepository,
   IRepository<Domain.UEPP_Qyjbxx> UEPP_QyjbxxRepository,
   IRepository<Domain.UEPP_QyRy> UEPP_QyRyRepository,
   IRepository<Domain.UEPP_Ryjbxx> UEPP_RyjbxxRepository,
   IRepository<Domain.UserInfo> UserInfoRepository,
   IRepository<Domain.wdecolinf> wdecolinfRepository,
   IRepository<Domain.wdetabinf> wdetabinfRepository,


IDbContext _dbcontext;
IRedis _redishelper;
IEventPublisher _eventPublisher;
ILogger _logger;

 ){
     _d_qyjjlxRepository = d_qyjjlxRepository;
   _g_BusinessLogRepository = g_BusinessLogRepository;
   _g_statetransferruleRepository = g_statetransferruleRepository;
   _gczj_codeRepository = gczj_codeRepository;
   _gczj_glyh_dqRepository = gczj_glyh_dqRepository;
   _gczj_jgjs_dwgcxxbRepository = gczj_jgjs_dwgcxxbRepository;
   _gczj_jgjsglbRepository = gczj_jgjsglbRepository;
   _gczj_jjscglbRepository = gczj_jjscglbRepository;
   _gczj_sgcsfhdglbRepository = gczj_sgcsfhdglbRepository;
   _gczj_xmxxRepository = gczj_xmxxRepository;
   _gczj_zbkzjba_xmzRepository = gczj_zbkzjba_xmzRepository;
   _gczj_zbkzjbaglbRepository = gczj_zbkzjbaglbRepository;
   _gczj_zbkzjbaglb_20140709Repository = gczj_zbkzjbaglb_20140709Repository;
   _gczj_zbkzjbaglb_20150610Repository = gczj_zbkzjbaglb_20150610Repository;
   _jsdw_jbqkbRepository = jsdw_jbqkbRepository;
   _org_businessRepository = org_businessRepository;
   _sgtyk_gljsryqkbRepository = sgtyk_gljsryqkbRepository;
   _sgtyk_qyjbqkbRepository = sgtyk_qyjbqkbRepository;
   _UEPP_CodeRepository = UEPP_CodeRepository;
   _UEPP_QycsywRepository = UEPP_QycsywRepository;
   _UEPP_QyjbxxRepository = UEPP_QyjbxxRepository;
   _UEPP_QyRyRepository = UEPP_QyRyRepository;
   _UEPP_RyjbxxRepository = UEPP_RyjbxxRepository;
   _UserInfoRepository = UserInfoRepository;
   _wdecolinfRepository = wdecolinfRepository;
   _wdetabinfRepository = wdetabinfRepository;

            this._dbcontext = dbcontext;
            this._eventPublisher = eventPublisher;
           this._redishelper = redishelper;
            this._logger = logger;
 

 }

  base(
       d_qyjjlxRepository,
   g_BusinessLogRepository,
   g_statetransferruleRepository,
   gczj_codeRepository,
   gczj_glyh_dqRepository,
   gczj_jgjs_dwgcxxbRepository,
   gczj_jgjsglbRepository,
   gczj_jjscglbRepository,
   gczj_sgcsfhdglbRepository,
   gczj_xmxxRepository,
   gczj_zbkzjba_xmzRepository,
   gczj_zbkzjbaglbRepository,
   gczj_zbkzjbaglb_20140709Repository,
   gczj_zbkzjbaglb_20150610Repository,
   jsdw_jbqkbRepository,
   org_businessRepository,
   sgtyk_gljsryqkbRepository,
   sgtyk_qyjbqkbRepository,
   UEPP_CodeRepository,
   UEPP_QycsywRepository,
   UEPP_QyjbxxRepository,
   UEPP_QyRyRepository,
   UEPP_RyjbxxRepository,
   UserInfoRepository,
   wdecolinfRepository,
   wdetabinfRepository,

 dbcontext,
 redishelper,
 eventPublisher,
 logger

 )

}

