//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

  void Addd_qyjjlx(d_qyjjlxDto d_qyjjlx);

   void Updated_qyjjlx(d_qyjjlxDto d_qyjjlx);


    d_qyjjlxDto Getd_qyjjlxById(int id);
	
		  List<d_qyjjlxDto> Getd_qyjjlxList(int? hotelid);
	

	  IPagedList<d_qyjjlxDto> Getd_qyjjlxList(int? hotelid,int pageindex, int pagesize);
	

	   void Deleted_qyjjlx(int id);
	

  void Addg_BusinessLog(g_BusinessLogDto g_BusinessLog);

   void Updateg_BusinessLog(g_BusinessLogDto g_BusinessLog);


    g_BusinessLogDto Getg_BusinessLogById(int id);
	
		  List<g_BusinessLogDto> Getg_BusinessLogList(int? hotelid);
	

	  IPagedList<g_BusinessLogDto> Getg_BusinessLogList(int? hotelid,int pageindex, int pagesize);
	

	   void Deleteg_BusinessLog(int id);
	

  void Addg_statetransferrule(g_statetransferruleDto g_statetransferrule);

   void Updateg_statetransferrule(g_statetransferruleDto g_statetransferrule);


    g_statetransferruleDto Getg_statetransferruleById(int id);
	
		  List<g_statetransferruleDto> Getg_statetransferruleList(int? hotelid);
	

	  IPagedList<g_statetransferruleDto> Getg_statetransferruleList(int? hotelid,int pageindex, int pagesize);
	

	   void Deleteg_statetransferrule(int id);
	

  void Addgczj_code(gczj_codeDto gczj_code);

   void Updategczj_code(gczj_codeDto gczj_code);


    gczj_codeDto Getgczj_codeById(int id);
	
		  List<gczj_codeDto> Getgczj_codeList(int? hotelid);
	

	  IPagedList<gczj_codeDto> Getgczj_codeList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_code(int id);
	

  void Addgczj_glyh_dq(gczj_glyh_dqDto gczj_glyh_dq);

   void Updategczj_glyh_dq(gczj_glyh_dqDto gczj_glyh_dq);


    gczj_glyh_dqDto Getgczj_glyh_dqById(int id);
	
		  List<gczj_glyh_dqDto> Getgczj_glyh_dqList(int? hotelid);
	

	  IPagedList<gczj_glyh_dqDto> Getgczj_glyh_dqList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_glyh_dq(int id);
	

  void Addgczj_jgjs_dwgcxxb(gczj_jgjs_dwgcxxbDto gczj_jgjs_dwgcxxb);

   void Updategczj_jgjs_dwgcxxb(gczj_jgjs_dwgcxxbDto gczj_jgjs_dwgcxxb);


    gczj_jgjs_dwgcxxbDto Getgczj_jgjs_dwgcxxbById(int id);
	
		  List<gczj_jgjs_dwgcxxbDto> Getgczj_jgjs_dwgcxxbList(int? hotelid);
	

	  IPagedList<gczj_jgjs_dwgcxxbDto> Getgczj_jgjs_dwgcxxbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_jgjs_dwgcxxb(int id);
	

  void Addgczj_jgjsglb(gczj_jgjsglbDto gczj_jgjsglb);

   void Updategczj_jgjsglb(gczj_jgjsglbDto gczj_jgjsglb);


    gczj_jgjsglbDto Getgczj_jgjsglbById(int id);
	
		  List<gczj_jgjsglbDto> Getgczj_jgjsglbList(int? hotelid);
	

	  IPagedList<gczj_jgjsglbDto> Getgczj_jgjsglbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_jgjsglb(int id);
	

  void Addgczj_jjscglb(gczj_jjscglbDto gczj_jjscglb);

   void Updategczj_jjscglb(gczj_jjscglbDto gczj_jjscglb);


    gczj_jjscglbDto Getgczj_jjscglbById(int id);
	
		  List<gczj_jjscglbDto> Getgczj_jjscglbList(int? hotelid);
	

	  IPagedList<gczj_jjscglbDto> Getgczj_jjscglbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_jjscglb(int id);
	

  void Addgczj_sgcsfhdglb(gczj_sgcsfhdglbDto gczj_sgcsfhdglb);

   void Updategczj_sgcsfhdglb(gczj_sgcsfhdglbDto gczj_sgcsfhdglb);


    gczj_sgcsfhdglbDto Getgczj_sgcsfhdglbById(int id);
	
		  List<gczj_sgcsfhdglbDto> Getgczj_sgcsfhdglbList(int? hotelid);
	

	  IPagedList<gczj_sgcsfhdglbDto> Getgczj_sgcsfhdglbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_sgcsfhdglb(int id);
	

  void Addgczj_xmxx(gczj_xmxxDto gczj_xmxx);

   void Updategczj_xmxx(gczj_xmxxDto gczj_xmxx);


    gczj_xmxxDto Getgczj_xmxxById(int id);
	
		  List<gczj_xmxxDto> Getgczj_xmxxList(int? hotelid);
	

	  IPagedList<gczj_xmxxDto> Getgczj_xmxxList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_xmxx(int id);
	

  void Addgczj_zbkzjba_xmz(gczj_zbkzjba_xmzDto gczj_zbkzjba_xmz);

   void Updategczj_zbkzjba_xmz(gczj_zbkzjba_xmzDto gczj_zbkzjba_xmz);


    gczj_zbkzjba_xmzDto Getgczj_zbkzjba_xmzById(int id);
	
		  List<gczj_zbkzjba_xmzDto> Getgczj_zbkzjba_xmzList(int? hotelid);
	

	  IPagedList<gczj_zbkzjba_xmzDto> Getgczj_zbkzjba_xmzList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_zbkzjba_xmz(int id);
	

  void Addgczj_zbkzjbaglb(gczj_zbkzjbaglbDto gczj_zbkzjbaglb);

   void Updategczj_zbkzjbaglb(gczj_zbkzjbaglbDto gczj_zbkzjbaglb);


    gczj_zbkzjbaglbDto Getgczj_zbkzjbaglbById(int id);
	
		  List<gczj_zbkzjbaglbDto> Getgczj_zbkzjbaglbList(int? hotelid);
	

	  IPagedList<gczj_zbkzjbaglbDto> Getgczj_zbkzjbaglbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_zbkzjbaglb(int id);
	

  void Addgczj_zbkzjbaglb_20140709(gczj_zbkzjbaglb_20140709Dto gczj_zbkzjbaglb_20140709);

   void Updategczj_zbkzjbaglb_20140709(gczj_zbkzjbaglb_20140709Dto gczj_zbkzjbaglb_20140709);


    gczj_zbkzjbaglb_20140709Dto Getgczj_zbkzjbaglb_20140709ById(int id);
	
		  List<gczj_zbkzjbaglb_20140709Dto> Getgczj_zbkzjbaglb_20140709List(int? hotelid);
	

	  IPagedList<gczj_zbkzjbaglb_20140709Dto> Getgczj_zbkzjbaglb_20140709List(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_zbkzjbaglb_20140709(int id);
	

  void Addgczj_zbkzjbaglb_20150610(gczj_zbkzjbaglb_20150610Dto gczj_zbkzjbaglb_20150610);

   void Updategczj_zbkzjbaglb_20150610(gczj_zbkzjbaglb_20150610Dto gczj_zbkzjbaglb_20150610);


    gczj_zbkzjbaglb_20150610Dto Getgczj_zbkzjbaglb_20150610ById(int id);
	
		  List<gczj_zbkzjbaglb_20150610Dto> Getgczj_zbkzjbaglb_20150610List(int? hotelid);
	

	  IPagedList<gczj_zbkzjbaglb_20150610Dto> Getgczj_zbkzjbaglb_20150610List(int? hotelid,int pageindex, int pagesize);
	

	   void Deletegczj_zbkzjbaglb_20150610(int id);
	

  void Addjsdw_jbqkb(jsdw_jbqkbDto jsdw_jbqkb);

   void Updatejsdw_jbqkb(jsdw_jbqkbDto jsdw_jbqkb);


    jsdw_jbqkbDto Getjsdw_jbqkbById(int id);
	
		  List<jsdw_jbqkbDto> Getjsdw_jbqkbList(int? hotelid);
	

	  IPagedList<jsdw_jbqkbDto> Getjsdw_jbqkbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletejsdw_jbqkb(int id);
	

  void Addorg_business(org_businessDto org_business);

   void Updateorg_business(org_businessDto org_business);


    org_businessDto Getorg_businessById(int id);
	
		  List<org_businessDto> Getorg_businessList(int? hotelid);
	

	  IPagedList<org_businessDto> Getorg_businessList(int? hotelid,int pageindex, int pagesize);
	

	   void Deleteorg_business(int id);
	

  void Addsgtyk_gljsryqkb(sgtyk_gljsryqkbDto sgtyk_gljsryqkb);

   void Updatesgtyk_gljsryqkb(sgtyk_gljsryqkbDto sgtyk_gljsryqkb);


    sgtyk_gljsryqkbDto Getsgtyk_gljsryqkbById(int id);
	
		  List<sgtyk_gljsryqkbDto> Getsgtyk_gljsryqkbList(int? hotelid);
	

	  IPagedList<sgtyk_gljsryqkbDto> Getsgtyk_gljsryqkbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletesgtyk_gljsryqkb(int id);
	

  void Addsgtyk_qyjbqkb(sgtyk_qyjbqkbDto sgtyk_qyjbqkb);

   void Updatesgtyk_qyjbqkb(sgtyk_qyjbqkbDto sgtyk_qyjbqkb);


    sgtyk_qyjbqkbDto Getsgtyk_qyjbqkbById(int id);
	
		  List<sgtyk_qyjbqkbDto> Getsgtyk_qyjbqkbList(int? hotelid);
	

	  IPagedList<sgtyk_qyjbqkbDto> Getsgtyk_qyjbqkbList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletesgtyk_qyjbqkb(int id);
	

  void AddUEPP_Code(UEPP_CodeDto UEPP_Code);

   void UpdateUEPP_Code(UEPP_CodeDto UEPP_Code);


    UEPP_CodeDto GetUEPP_CodeById(int id);
	
		  List<UEPP_CodeDto> GetUEPP_CodeList(int? hotelid);
	

	  IPagedList<UEPP_CodeDto> GetUEPP_CodeList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUEPP_Code(int id);
	

  void AddUEPP_Qycsyw(UEPP_QycsywDto UEPP_Qycsyw);

   void UpdateUEPP_Qycsyw(UEPP_QycsywDto UEPP_Qycsyw);


    UEPP_QycsywDto GetUEPP_QycsywById(int id);
	
		  List<UEPP_QycsywDto> GetUEPP_QycsywList(int? hotelid);
	

	  IPagedList<UEPP_QycsywDto> GetUEPP_QycsywList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUEPP_Qycsyw(int id);
	

  void AddUEPP_Qyjbxx(UEPP_QyjbxxDto UEPP_Qyjbxx);

   void UpdateUEPP_Qyjbxx(UEPP_QyjbxxDto UEPP_Qyjbxx);


    UEPP_QyjbxxDto GetUEPP_QyjbxxById(int id);
	
		  List<UEPP_QyjbxxDto> GetUEPP_QyjbxxList(int? hotelid);
	

	  IPagedList<UEPP_QyjbxxDto> GetUEPP_QyjbxxList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUEPP_Qyjbxx(int id);
	

  void AddUEPP_QyRy(UEPP_QyRyDto UEPP_QyRy);

   void UpdateUEPP_QyRy(UEPP_QyRyDto UEPP_QyRy);


    UEPP_QyRyDto GetUEPP_QyRyById(int id);
	
		  List<UEPP_QyRyDto> GetUEPP_QyRyList(int? hotelid);
	

	  IPagedList<UEPP_QyRyDto> GetUEPP_QyRyList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUEPP_QyRy(int id);
	

  void AddUEPP_Ryjbxx(UEPP_RyjbxxDto UEPP_Ryjbxx);

   void UpdateUEPP_Ryjbxx(UEPP_RyjbxxDto UEPP_Ryjbxx);


    UEPP_RyjbxxDto GetUEPP_RyjbxxById(int id);
	
		  List<UEPP_RyjbxxDto> GetUEPP_RyjbxxList(int? hotelid);
	

	  IPagedList<UEPP_RyjbxxDto> GetUEPP_RyjbxxList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUEPP_Ryjbxx(int id);
	

  void AddUserInfo(UserInfoDto UserInfo);

   void UpdateUserInfo(UserInfoDto UserInfo);


    UserInfoDto GetUserInfoById(int id);
	
		  List<UserInfoDto> GetUserInfoList(int? hotelid);
	

	  IPagedList<UserInfoDto> GetUserInfoList(int? hotelid,int pageindex, int pagesize);
	

	   void DeleteUserInfo(int id);
	

  void Addwdecolinf(wdecolinfDto wdecolinf);

   void Updatewdecolinf(wdecolinfDto wdecolinf);


    wdecolinfDto GetwdecolinfById(int id);
	
		  List<wdecolinfDto> GetwdecolinfList(int? hotelid);
	

	  IPagedList<wdecolinfDto> GetwdecolinfList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletewdecolinf(int id);
	

  void Addwdetabinf(wdetabinfDto wdetabinf);

   void Updatewdetabinf(wdetabinfDto wdetabinf);


    wdetabinfDto GetwdetabinfById(int id);
	
		  List<wdetabinfDto> GetwdetabinfList(int? hotelid);
	

	  IPagedList<wdetabinfDto> GetwdetabinfList(int? hotelid,int pageindex, int pagesize);
	

	   void Deletewdetabinf(int id);
	


