//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddPrice
    {
        public int Id { get; set; }
        public Nullable<int> hotel { get; set; }
        public Nullable<int> AddPice { get; set; }
        public Nullable<int> ZsPice { get; set; }
        public Nullable<int> ZsJf { get; set; }
        public Nullable<bool> IsOk { get; set; }
        public string Remark { get; set; }
    }
}
