//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class FtSet
    {
        public int Id { get; set; }
        public Nullable<int> hotelid { get; set; }
        public int Lwidth { get; set; }
        public int Lhieght { get; set; }
        public string Lfontf { get; set; }
        public int Fontsize { get; set; }
        public Nullable<int> Lmargin { get; set; }
        public string Backcolor { get; set; }
        public string Bordercolor { get; set; }
        public Nullable<bool> showType { get; set; }
        public Nullable<bool> showPrice { get; set; }
        public Nullable<bool> orderLC { get; set; }
        public int ftNum { get; set; }
        public Nullable<bool> zzShowType { get; set; }
        public Nullable<bool> zzShowPrice { get; set; }
        public Nullable<bool> showFormTime { get; set; }
        public Nullable<bool> showLFico { get; set; }
        public Nullable<bool> showBmico { get; set; }
        public Nullable<bool> showyjb { get; set; }
        public Nullable<bool> showday { get; set; }
        public Nullable<int> daynum { get; set; }
        public Nullable<bool> showyue { get; set; }
        public Nullable<int> moneyNum { get; set; }
        public Nullable<bool> showcf { get; set; }
        public Nullable<bool> showThem { get; set; }
        public string Themtext { get; set; }
        public Nullable<bool> showMember { get; set; }
        public string memberText { get; set; }
        public Nullable<bool> showXy { get; set; }
        public Nullable<bool> showYuli { get; set; }
        public Nullable<bool> yuliDay { get; set; }
        public Nullable<bool> showDayTime { get; set; }
        public Nullable<int> dayNumYl { get; set; }
        public Nullable<bool> showxz { get; set; }
        public Nullable<bool> showSf { get; set; }
        public Nullable<bool> showYuee { get; set; }
        public Nullable<bool> Showzdftime { get; set; }
        public Nullable<bool> Showbooktime { get; set; }
        public Nullable<bool> Showzf { get; set; }
        public Nullable<bool> Showlc { get; set; }
        public Nullable<bool> showPeoNum { get; set; }
        public Nullable<bool> showRk { get; set; }
        public Nullable<bool> showWupi { get; set; }
        public Nullable<bool> Showyz { get; set; }
        public Nullable<bool> Showmf { get; set; }
        public Nullable<bool> Showzdf { get; set; }
        public Nullable<bool> Beiy { get; set; }
        public Nullable<bool> Beiy2 { get; set; }
        public Nullable<int> numSize { get; set; }
        public string numColor { get; set; }
        public Nullable<int> fxSize { get; set; }
        public string fxColor { get; set; }
        public Nullable<int> yueSize { get; set; }
        public string yueColor { get; set; }
        public Nullable<int> nameSize { get; set; }
        public string nameColor { get; set; }
        public Nullable<int> priceSize { get; set; }
        public string priceColor { get; set; }
        public Nullable<int> TotimeSize { get; set; }
        public string TotimeColor { get; set; }
        public Nullable<int> zdSize { get; set; }
        public string zdColor { get; set; }
        public Nullable<int> icoColor { get; set; }
    }
}
