//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_BusinessLog
    {
        public long LogID { get; set; }
        public string SystemName { get; set; }
        public string ModuleName { get; set; }
        public string CategoryName { get; set; }
        public string KeyString { get; set; }
        public string Operation { get; set; }
        public string PriorStatus { get; set; }
        public string PostStatus { get; set; }
        public string MessageInfo { get; set; }
        public string OperatorID { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime OperateDateTime { get; set; }
    }
}
