//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_jjscglb
    {
        public int BusinessId { get; set; }
        public string yscbh { get; set; }
        public string scbh { get; set; }
        public string qyID { get; set; }
        public string qymc { get; set; }
        public string zzzsh { get; set; }
        public string zzdj { get; set; }
        public string fddbr { get; set; }
        public string qyxzID { get; set; }
        public string qyxz { get; set; }
        public Nullable<System.DateTime> clrq { get; set; }
        public string lxr { get; set; }
        public string lxdh { get; set; }
        public string yzbm { get; set; }
        public string zcdz { get; set; }
        public string yb { get; set; }
        public string zsdz { get; set; }
        public string yyzzzch { get; set; }
        public string zzjgdm { get; set; }
        public string sgqy { get; set; }
        public string cbfw { get; set; }
        public Nullable<System.DateTime> scyxqsrq { get; set; }
        public Nullable<System.DateTime> scyxjsrq { get; set; }
        public string bz { get; set; }
        public string bgsx { get; set; }
        public string bgq { get; set; }
        public string bgh { get; set; }
        public string hfjgid { get; set; }
        public string hfjg { get; set; }
        public Nullable<System.DateTime> hfrq { get; set; }
        public int DataState { get; set; }
        public int OperateState { get; set; }
        public int CancelState { get; set; }
        public Nullable<System.DateTime> cjrqsj { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public Nullable<System.DateTime> sbrqsj { get; set; }
        public Nullable<long> txr_UserID { get; set; }
        public string txr_UserName { get; set; }
        public string tbr { get; set; }
        public string tbrdh { get; set; }
        public int Checkbz1 { get; set; }
        public string shyj1 { get; set; }
        public Nullable<System.DateTime> shrqsj1 { get; set; }
        public Nullable<long> checkUserID1 { get; set; }
        public string checkUserName1 { get; set; }
        public string checkdeptcode1 { get; set; }
        public string checkdeptname1 { get; set; }
        public int Checkbz2 { get; set; }
        public string Shyj2 { get; set; }
        public Nullable<System.DateTime> Shrqsj2 { get; set; }
        public Nullable<long> checkUserID2 { get; set; }
        public string checkUserName2 { get; set; }
        public string checkdeptcode2 { get; set; }
        public string checkdeptname2 { get; set; }
        public int Checkbz3 { get; set; }
        public string Shyj3 { get; set; }
        public Nullable<System.DateTime> Shrqsj3 { get; set; }
        public Nullable<long> checkUserID3 { get; set; }
        public string checkUserName3 { get; set; }
        public string checkdeptcode3 { get; set; }
        public string checkdeptname3 { get; set; }
    }
}
