//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_jgjs_dwgcxxb
    {
        public int dwgcId { get; set; }
        public int BusinessId { get; set; }
        public string dwgcms { get; set; }
        public string gczylbbh { get; set; }
        public string gczylb { get; set; }
        public string jsbzrid { get; set; }
        public string jsbzr { get; set; }
        public string o { get; set; }
        public string jsshr { get; set; }
        public Nullable<decimal> ssj { get; set; }
        public Nullable<decimal> sdj { get; set; }
        public short DataState { get; set; }
    }
}
