//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_zbkzjbaglb_20140709
    {
        public int businessID { get; set; }
        public string gcmc { get; set; }
        public string gcdz { get; set; }
        public string gm { get; set; }
        public string zxzy { get; set; }
        public string htbhxmmc { get; set; }
        public Nullable<decimal> zbkzj { get; set; }
        public Nullable<System.DateTime> kbsj { get; set; }
        public string gctzms { get; set; }
        public string gclb { get; set; }
        public string degq { get; set; }
        public string zbgq { get; set; }
        public string bdjjwj { get; set; }
        public string cbjpsbwj { get; set; }
        public string zbkzjbcb { get; set; }
        public string gclzhfxb { get; set; }
        public string csfyfxb { get; set; }
        public string zjzxdwID { get; set; }
        public string zjzxdw { get; set; }
        public string zjzxdwzzdj { get; set; }
        public string jsdwID { get; set; }
        public string jsdw { get; set; }
        public int DataState { get; set; }
        public int OperateState { get; set; }
        public int CancelState { get; set; }
        public Nullable<System.DateTime> cjrqsj { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public Nullable<long> txr_UserID { get; set; }
        public string txr_UserName { get; set; }
        public int Checkbz1 { get; set; }
        public string shyj1 { get; set; }
        public Nullable<System.DateTime> shrqsj1 { get; set; }
        public Nullable<long> checkUserID1 { get; set; }
        public string checkUserName1 { get; set; }
        public string checkdeptcode1 { get; set; }
        public string checkdeptname1 { get; set; }
        public int Checkbz2 { get; set; }
        public string Shyj2 { get; set; }
        public Nullable<System.DateTime> Shrqsj2 { get; set; }
        public Nullable<long> checkUserID2 { get; set; }
        public string checkUserName2 { get; set; }
        public string checkdeptcode2 { get; set; }
        public string checkdeptname2 { get; set; }
        public int Checkbz3 { get; set; }
        public string Shyj3 { get; set; }
        public Nullable<System.DateTime> Shrqsj3 { get; set; }
        public Nullable<long> checkUserID3 { get; set; }
        public string checkUserName3 { get; set; }
        public string checkdeptcode3 { get; set; }
        public string checkdeptname3 { get; set; }
    }
}
