//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_zbkzjba_xmz
    {
        public long Id { get; set; }
        public int businessID { get; set; }
        public string cyid { get; set; }
        public string cymc { get; set; }
        public string zjszczh { get; set; }
        public string zjyzh { get; set; }
        public string zjyzy { get; set; }
        public string zjydj { get; set; }
        public short datastate { get; set; }
        public string cylb { get; set; }
        public string zjszy { get; set; }
        public string rylb { get; set; }
    }
}
