//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_sgcsfhdglb
    {
        public int BusinessId { get; set; }
        public Nullable<int> xmID { get; set; }
        public string Tykxmid { get; set; }
        public string sgcsfhdh { get; set; }
        public string gcmc { get; set; }
        public string gcdz { get; set; }
        public string gclx { get; set; }
        public string gctz { get; set; }
        public string gm { get; set; }
        public string ssdqID { get; set; }
        public string ssdq { get; set; }
        public string jsdwID { get; set; }
        public string jsdw { get; set; }
        public string jsdwZzjgdm { get; set; }
        public string jsdwzzdj { get; set; }
        public string jsdwdz { get; set; }
        public string jsdwyb { get; set; }
        public string jsdwlxr { get; set; }
        public string jsdwlxrdh { get; set; }
        public string jsdwlxrsfz { get; set; }
        public string jsdwdh { get; set; }
        public string sgdwid { get; set; }
        public string sgdw { get; set; }
        public string sgdwzzjgdm { get; set; }
        public string sgdwdz { get; set; }
        public string sgdwyb { get; set; }
        public string sgdwlxr { get; set; }
        public string sgdwlxdh { get; set; }
        public string sgdwlxrdh { get; set; }
        public string sgdwlxrsfz { get; set; }
        public string sgdwxmfzrid { get; set; }
        public string sgdwxmfzr { get; set; }
        public string sgdwxmfzrlxdh { get; set; }
        public string zjzxdwID { get; set; }
        public string zjzxdw { get; set; }
        public string zjzxdwZzjgdm { get; set; }
        public string zjzxdwdz { get; set; }
        public string zjzxdwyb { get; set; }
        public string zjxmfzrid { get; set; }
        public string zjxmfzr { get; set; }
        public string sfzb { get; set; }
        public Nullable<System.DateTime> zbsj { get; set; }
        public Nullable<System.DateTime> sssj { get; set; }
        public Nullable<System.DateTime> sbsj { get; set; }
        public Nullable<decimal> zbj { get; set; }
        public Nullable<decimal> htj { get; set; }
        public Nullable<decimal> ssj { get; set; }
        public string wmgd { get; set; }
        public short jgjsbz { get; set; }
        public string xmjl { get; set; }
        public string xmjllxdh { get; set; }
        public int DataState { get; set; }
        public int OperateState { get; set; }
        public int CancelState { get; set; }
        public Nullable<System.DateTime> cjrqsj { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public Nullable<long> txr_UserID { get; set; }
        public string txr_UserName { get; set; }
        public int Checkbz1 { get; set; }
        public string shyj1 { get; set; }
        public Nullable<System.DateTime> shrqsj1 { get; set; }
        public Nullable<long> checkUserID1 { get; set; }
        public string checkUserName1 { get; set; }
        public string checkdeptcode1 { get; set; }
        public string checkdeptname1 { get; set; }
        public int Checkbz2 { get; set; }
        public string Shyj2 { get; set; }
        public Nullable<System.DateTime> Shrqsj2 { get; set; }
        public Nullable<long> checkUserID2 { get; set; }
        public string checkUserName2 { get; set; }
        public string checkdeptcode2 { get; set; }
        public string checkdeptname2 { get; set; }
        public int Checkbz3 { get; set; }
        public string Shyj3 { get; set; }
        public Nullable<System.DateTime> Shrqsj3 { get; set; }
        public Nullable<long> checkUserID3 { get; set; }
        public string checkUserName3 { get; set; }
        public string checkdeptcode3 { get; set; }
        public string checkdeptname3 { get; set; }
    }
}
