//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class gczj_xmxx
    {
        public long xmID { get; set; }
        public string flowSN { get; set; }
        public string gcmc { get; set; }
        public string gcdz { get; set; }
        public string gm { get; set; }
        public string jsdw { get; set; }
        public string sgdw { get; set; }
        public Nullable<decimal> htj { get; set; }
        public short DataState { get; set; }
    }
}
