//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsdw_jbqkb
    {
        public string qyId { get; set; }
        public Nullable<int> LoginId { get; set; }
        public string qymc { get; set; }
        public string zzjgdm { get; set; }
        public string qylx { get; set; }
        public string qydz { get; set; }
        public string frdb { get; set; }
        public string frdbdh { get; set; }
        public string lxr { get; set; }
        public string lxdh { get; set; }
        public string Zzdj { get; set; }
        public string Zzzsh { get; set; }
        public Nullable<System.DateTime> Zzzsjzrq { get; set; }
    }
}
