//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberType
    {
        public int Id { get; set; }
        public Nullable<int> hotelid { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> typePrice { get; set; }
        public Nullable<bool> Limit { get; set; }
        public Nullable<int> LimitValue { get; set; }
        public Nullable<bool> IntegraIs { get; set; }
        public Nullable<bool> IsConsump { get; set; }
        public Nullable<bool> IsFz { get; set; }
        public Nullable<bool> IsXf { get; set; }
        public Nullable<int> XfPrice { get; set; }
        public Nullable<int> XfConsump { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<int> LiveNum { get; set; }
        public Nullable<int> LiveConsump { get; set; }
        public Nullable<bool> IsTx { get; set; }
        public Nullable<bool> IsDeaflut { get; set; }
        public Nullable<bool> IsUpgrade { get; set; }
        public Nullable<int> ConsumpSum { get; set; }
        public Nullable<int> UpLive { get; set; }
        public Nullable<bool> IsDeduction { get; set; }
        public Nullable<bool> Isout { get; set; }
        public Nullable<int> OutHour { get; set; }
        public Nullable<int> OutZD { get; set; }
        public Nullable<int> FirstPrice { get; set; }
        public Nullable<int> StaPrice { get; set; }
        public Nullable<System.DateTime> XqTime { get; set; }
        public Nullable<int> machJf { get; set; }
    }
}
