//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class meth_pay
    {
        public int Id { get; set; }
        public string meth_pay_name { get; set; }
        public Nullable<bool> meth_is_ya { get; set; }
        public Nullable<bool> meth_is_jie { get; set; }
        public Nullable<int> meth_sort { get; set; }
        public string remark { get; set; }
    }
}
