//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EM_TestEntities : DbContext
    {
        public EM_TestEntities()
            : base("name=EM_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d_qyjjlx> d_qyjjlx { get; set; }
        public virtual DbSet<g_BusinessLog> g_BusinessLog { get; set; }
        public virtual DbSet<g_statetransferrule> g_statetransferrule { get; set; }
        public virtual DbSet<gczj_code> gczj_code { get; set; }
        public virtual DbSet<gczj_glyh_dq> gczj_glyh_dq { get; set; }
        public virtual DbSet<gczj_jgjs_dwgcxxb> gczj_jgjs_dwgcxxb { get; set; }
        public virtual DbSet<gczj_jgjsglb> gczj_jgjsglb { get; set; }
        public virtual DbSet<gczj_jjscglb> gczj_jjscglb { get; set; }
        public virtual DbSet<gczj_sgcsfhdglb> gczj_sgcsfhdglb { get; set; }
        public virtual DbSet<gczj_xmxx> gczj_xmxx { get; set; }
        public virtual DbSet<gczj_zbkzjba_xmz> gczj_zbkzjba_xmz { get; set; }
        public virtual DbSet<gczj_zbkzjbaglb> gczj_zbkzjbaglb { get; set; }
        public virtual DbSet<jsdw_jbqkb> jsdw_jbqkb { get; set; }
        public virtual DbSet<sgtyk_gljsryqkb> sgtyk_gljsryqkb { get; set; }
        public virtual DbSet<sgtyk_qyjbqkb> sgtyk_qyjbqkb { get; set; }
        public virtual DbSet<UEPP_Code> UEPP_Code { get; set; }
        public virtual DbSet<UEPP_Qycsyw> UEPP_Qycsyw { get; set; }
        public virtual DbSet<UEPP_Qyjbxx> UEPP_Qyjbxx { get; set; }
        public virtual DbSet<UEPP_QyRy> UEPP_QyRy { get; set; }
        public virtual DbSet<UEPP_Ryjbxx> UEPP_Ryjbxx { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<wdecolinf> wdecolinf { get; set; }
        public virtual DbSet<wdetabinf> wdetabinf { get; set; }
        public virtual DbSet<gczj_zbkzjbaglb_20140709> gczj_zbkzjbaglb_20140709 { get; set; }
        public virtual DbSet<gczj_zbkzjbaglb_20150610> gczj_zbkzjbaglb_20150610 { get; set; }
        public virtual DbSet<org_business> org_business { get; set; }
    }
}
