//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtPrice
    {
        public int Id { get; set; }
        public Nullable<int> hotelid { get; set; }
        public Nullable<int> MTID { get; set; }
        public Nullable<int> RoomType { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Dayprice { get; set; }
        public Nullable<double> zdPrice { get; set; }
        public Nullable<int> lcPrice { get; set; }
        public string mothPrice { get; set; }
    }
}
