//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class sgtyk_qyjbqkb
    {
        public string qyID { get; set; }
        public string zxlb_com { get; set; }
        public string qyfl_com { get; set; }
        public string balx_com { get; set; }
        public string qymc { get; set; }
        public string zzzsh { get; set; }
        public string Sscs_com { get; set; }
        public string Ssdq_com { get; set; }
        public string yyzzh { get; set; }
        public Nullable<System.DateTime> clsj { get; set; }
        public string jjxz_com { get; set; }
        public string zyfw { get; set; }
        public string jyfw { get; set; }
        public string qyjj { get; set; }
        public byte[] zzjgt { get; set; }
        public string zcdd { get; set; }
        public string yzbm { get; set; }
        public string xxdd { get; set; }
        public string yzbm2 { get; set; }
        public string cz { get; set; }
        public string email { get; set; }
        public string webAddress { get; set; }
        public string Qylxr { get; set; }
        public string qylxdh { get; set; }
        public string zs_dz { get; set; }
        public string zs_yyzzh { get; set; }
        public string zs_lxdh { get; set; }
        public string zs_yzbm { get; set; }
        public Nullable<int> nmrs { get; set; }
        public Nullable<int> nmltxrs { get; set; }
        public Nullable<int> pjrs { get; set; }
        public Nullable<int> glrs { get; set; }
        public Nullable<int> zzxlrs { get; set; }
        public Nullable<int> zcryrs { get; set; }
        public Nullable<int> zjzcrs { get; set; }
        public Nullable<int> gjzcrs { get; set; }
        public Nullable<int> gcjsryzs { get; set; }
        public Nullable<int> gcjsryzjzcrs { get; set; }
        public Nullable<int> gcjsrygjzcrs { get; set; }
        public Nullable<int> pytxjsryrs { get; set; }
        public Nullable<int> xmjlzs { get; set; }
        public Nullable<int> yjxmjlzs { get; set; }
        public Nullable<int> ejxmjlzs { get; set; }
        public Nullable<int> sjxmjlzs { get; set; }
        public Nullable<int> sgyrs { get; set; }
        public Nullable<int> zjyrs { get; set; }
        public Nullable<int> ysyrs { get; set; }
        public Nullable<int> aqyrs { get; set; }
        public Nullable<int> lwyrs { get; set; }
        public Nullable<int> sgcgszrs { get; set; }
        public Nullable<int> zjcgszrs { get; set; }
        public Nullable<int> yscgszrs { get; set; }
        public Nullable<int> aqcgszrs { get; set; }
        public Nullable<int> lwcgszrs { get; set; }
        public string dadbh { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string enterp_zzjgdm { get; set; }
        public string Zczb { get; set; }
        public string Sszb { get; set; }
        public string zs_lxr { get; set; }
        public string sbdq_com { get; set; }
        public string khyh { get; set; }
        public string yhzh { get; set; }
        public Nullable<bool> InGIS_zt { get; set; }
        public Nullable<bool> Visible { get; set; }
    }
}
