//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class sgtyk_gljsryqkb
    {
        public long ryID { get; set; }
        public string qyID { get; set; }
        public string name { get; set; }
        public string lx_com { get; set; }
        public string ryfl_com { get; set; }
        public string sex_com { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public string zw_com { get; set; }
        public string zc_com { get; set; }
        public string xl_com { get; set; }
        public Nullable<System.DateTime> bysj { get; set; }
        public string byyx { get; set; }
        public string zy { get; set; }
        public string gcglzl { get; set; }
        public string sj { get; set; }
        public string Zp_RealFileName { get; set; }
        public string Zp_FileName { get; set; }
        public Nullable<long> Zp_FileSize { get; set; }
        public byte[] Zp_FileContent { get; set; }
        public string sfzh { get; set; }
        public string zcbh { get; set; }
        public string zczsbh { get; set; }
        public string zczsfzdw { get; set; }
        public Nullable<System.DateTime> zczsyxqrq { get; set; }
        public Nullable<System.DateTime> zczsyxzrq { get; set; }
        public string zczlj { get; set; }
    }
}
