//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEPP_Ryjbxx
    {
        public int ryID { get; set; }
        public string xm { get; set; }
        public string xb { get; set; }
        public Nullable<System.DateTime> csrq { get; set; }
        public string jkzt { get; set; }
        public string mz { get; set; }
        public Nullable<int> xlID { get; set; }
        public string xl { get; set; }
        public string sxzy { get; set; }
        public string byyx { get; set; }
        public Nullable<System.DateTime> byny { get; set; }
        public Nullable<int> zcID { get; set; }
        public string zc { get; set; }
        public string zczh { get; set; }
        public Nullable<int> zcjbID { get; set; }
        public string zcjb { get; set; }
        public Nullable<int> zczyID { get; set; }
        public string zczy { get; set; }
        public string csgzjsnx { get; set; }
        public string lxdh { get; set; }
        public string yddh { get; set; }
        public string gzjl { get; set; }
        public string bz { get; set; }
        public string slbmID { get; set; }
        public string slbm { get; set; }
        public short DataState { get; set; }
        public Nullable<System.DateTime> cjrqsj { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public Nullable<System.DateTime> sbrqsj { get; set; }
        public Nullable<System.DateTime> bgrqsj { get; set; }
        public Nullable<System.DateTime> bgsbrqsj { get; set; }
        public string shyj { get; set; }
        public Nullable<System.DateTime> shrqsj { get; set; }
        public Nullable<int> shr_UserID { get; set; }
        public string shr_UserName { get; set; }
        public string zyzgId { get; set; }
        public string zyzg { get; set; }
        public Nullable<System.DateTime> pdsj { get; set; }
    }
}
