//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEPP_Qycsyw
    {
        public int Id { get; set; }
        public int qyID { get; set; }
        public int csywlxID { get; set; }
        public string csywlx { get; set; }
        public Nullable<int> balxID { get; set; }
        public string balx { get; set; }
        public short DataState { get; set; }
    }
}
