//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEPP_QyRy
    {
        public int ID { get; set; }
        public int qyID { get; set; }
        public Nullable<int> csywlxID { get; set; }
        public string csywlx { get; set; }
        public int ryID { get; set; }
        public Nullable<int> ryzyzglxID { get; set; }
        public string ryzyzglx { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public short DataState { get; set; }
    }
}
