//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoteManagement.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEPP_Qyjbxx
    {
        public int qyID { get; set; }
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public string qymc { get; set; }
        public string zzjgdm { get; set; }
        public string yyzzzch { get; set; }
        public string khyh { get; set; }
        public string yhzh { get; set; }
        public Nullable<int> sylxID { get; set; }
        public string sylx { get; set; }
        public string ProvinceID { get; set; }
        public string Province { get; set; }
        public string CityID { get; set; }
        public string City { get; set; }
        public string CountyID { get; set; }
        public string County { get; set; }
        public string zcdd { get; set; }
        public Nullable<int> jjxzID { get; set; }
        public string jjxz { get; set; }
        public Nullable<decimal> zczb { get; set; }
        public Nullable<decimal> sjzb { get; set; }
        public string zyfw { get; set; }
        public string jyfw { get; set; }
        public Nullable<System.DateTime> clrq { get; set; }
        public string qyjj { get; set; }
        public string xxdd { get; set; }
        public string yzbm { get; set; }
        public string cz { get; set; }
        public string email { get; set; }
        public string webAddress { get; set; }
        public string lxr { get; set; }
        public string lxdh { get; set; }
        public Nullable<int> fddbr_ryid { get; set; }
        public Nullable<int> qyfzr_ryid { get; set; }
        public Nullable<int> cwfzr_ryid { get; set; }
        public Nullable<int> jsfzr_ryid { get; set; }
        public Nullable<int> aqfzr_ryid { get; set; }
        public string slbmID { get; set; }
        public string slbm { get; set; }
        public short DataState { get; set; }
        public Nullable<System.DateTime> cjrqsj { get; set; }
        public Nullable<System.DateTime> xgrqsj { get; set; }
        public Nullable<System.DateTime> sbrqsj { get; set; }
        public Nullable<System.DateTime> bgrqsj { get; set; }
        public Nullable<System.DateTime> bgsbrqsj { get; set; }
        public string shyj { get; set; }
        public Nullable<System.DateTime> shrqsj { get; set; }
        public Nullable<int> shr_UserID { get; set; }
        public string shr_UserName { get; set; }
    }
}
