//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class breakfirstcouponMap : BaseEntityTypeConfiguration<HoteManagement.Domain.breakfirstcoupon>
    {
       public breakfirstcouponMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.time);
          this.Property(t => t.roomnum).HasMaxLength(50);
          this.Property(t => t.IsEnabled);
          this.Property(t => t.IsStandard);
          this.Property(t => t.IsUsed);
          this.Property(t => t.createor).HasMaxLength(50);
          this.Property(t => t.createtime);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
