//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class cprotocolMap : BaseEntityTypeConfiguration<HoteManagement.Domain.cprotocol>
    {
       public cprotocolMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.Accounts).HasMaxLength(50);
          this.Property(t => t.Ptheme).HasMaxLength(50);
          this.Property(t => t.pType);
          this.Property(t => t.PNumber).HasMaxLength(50);
          this.Property(t => t.ishire);
          this.Property(t => t.term);
          this.Property(t => t.period);
          this.Property(t => t.breakfast);
          this.Property(t => t.Commission);
          this.Property(t => t.Dayhire);
          this.Property(t => t.prohire);
          this.Property(t => t.signatory).HasMaxLength(50);
          this.Property(t => t.companysignatory).HasMaxLength(50);
          this.Property(t => t.roomNumber).HasMaxLength(50);
          this.Property(t => t.Isdiscount);
          this.Property(t => t.discount);
          this.Property(t => t.Remark).HasMaxLength(500);
          this.Property(t => t.isVerify);
          this.Property(t => t.editUser).HasMaxLength(50);
          this.Property(t => t.verifyUser);
          this.Property(t => t.Details).HasMaxLength(500);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
