//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class creditMap : BaseEntityTypeConfiguration<HoteManagement.Domain.credit>
    {
       public creditMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.customerid);
          this.Property(t => t.roomnum).HasMaxLength(50);
          this.Property(t => t.username).HasMaxLength(50);
          this.Property(t => t.no).HasMaxLength(50);
          this.Property(t => t.creditno).HasMaxLength(50);
          this.Property(t => t.expiredtime);
          this.Property(t => t.remark).HasMaxLength(250);
          this.Property(t => t.expire).HasMaxLength(10);
          this.Property(t => t.creditmoney);
          this.Property(t => t.authorizationcode).HasMaxLength(50);
          this.Property(t => t.documentno).HasMaxLength(50);
          this.Property(t => t.createtime);
          this.Property(t => t.creator).HasMaxLength(50);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
