//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class memberTypeMap : BaseEntityTypeConfiguration<HoteManagement.Domain.memberType>
    {
       public memberTypeMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.TypeName).HasMaxLength(50);
          this.Property(t => t.typePrice);
          this.Property(t => t.Limit);
          this.Property(t => t.LimitValue);
          this.Property(t => t.IntegraIs);
          this.Property(t => t.IsConsump);
          this.Property(t => t.IsFz);
          this.Property(t => t.IsXf);
          this.Property(t => t.XfPrice);
          this.Property(t => t.XfConsump);
          this.Property(t => t.IsLive);
          this.Property(t => t.LiveNum);
          this.Property(t => t.LiveConsump);
          this.Property(t => t.IsTx);
          this.Property(t => t.IsDeaflut);
          this.Property(t => t.IsUpgrade);
          this.Property(t => t.ConsumpSum);
          this.Property(t => t.UpLive);
          this.Property(t => t.IsDeduction);
          this.Property(t => t.Isout);
          this.Property(t => t.OutHour);
          this.Property(t => t.OutZD);
          this.Property(t => t.FirstPrice);
          this.Property(t => t.StaPrice);
          this.Property(t => t.XqTime);
          this.Property(t => t.machJf);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
