//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class mtPriceMap : BaseEntityTypeConfiguration<HoteManagement.Domain.mtPrice>
    {
       public mtPriceMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.MTID);
          this.Property(t => t.RoomType);
          this.Property(t => t.Price);
          this.Property(t => t.Dayprice);
          this.Property(t => t.zdPrice);
          this.Property(t => t.lcPrice);
          this.Property(t => t.mothPrice).HasMaxLength(10);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
