//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class order_extMap : BaseEntityTypeConfiguration<HoteManagement.Domain.order_ext>
    {
       public order_extMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.roomnum).HasMaxLength(50);
          this.Property(t => t.ordreno).HasMaxLength(50);
          this.Property(t => t.hotelid);
          this.Property(t => t.price);
          this.Property(t => t.name).HasMaxLength(50);
          this.Property(t => t.type);
          this.Property(t => t.num);
          this.Property(t => t.opentime);
          this.Property(t => t.creator).HasMaxLength(50);
          this.Property(t => t.createtime);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
