//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class Shift_ExcMap : BaseEntityTypeConfiguration<HoteManagement.Domain.Shift_Exc>
    {
       public Shift_ExcMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.UserId);
          this.Property(t => t.Good_Account_Id);
          this.Property(t => t.meth_pay_id);
          this.Property(t => t.shift_id);
          this.Property(t => t.shift_state).HasMaxLength(50);
          this.Property(t => t.shift_money);
          this.Property(t => t.shift_dateTime);
          this.Property(t => t.ga_name).HasMaxLength(50);
          this.Property(t => t.ga_number).HasMaxLength(50);
          this.Property(t => t.ga_unit).HasMaxLength(50);
          this.Property(t => t.ga_num);
          this.Property(t => t.ga_price);
          this.Property(t => t.ga_zffs_id);
          this.Property(t => t.ga_date);
          this.Property(t => t.ga_Type);
          this.Property(t => t.ga_sum_price);
          this.Property(t => t.Remark);
          this.Property(t => t.ga_roomNumber).HasMaxLength(50);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
