//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class SincethehousMap : BaseEntityTypeConfiguration<HoteManagement.Domain.Sincethehous>
    {
       public SincethehousMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.hs_Numberno).HasMaxLength(50);
          this.Property(t => t.hs_room).HasMaxLength(50);
          this.Property(t => t.hs_yuany);
          this.Property(t => t.hs_date);
          this.Property(t => t.hs_ksDate);
          this.Property(t => t.hs_ylDate).HasMaxLength(50);
          this.Property(t => t.hs_Documentno).HasMaxLength(50);
          this.Property(t => t.hs_type);
          this.Property(t => t.hs_people).HasMaxLength(50);
          this.Property(t => t.hs_Result);
          this.Property(t => t.hs_remaker);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
