//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class UserInfoMap : BaseEntityTypeConfiguration<HoteManagement.Domain.UserInfo>
    {
       public UserInfoMap()
       {
          this.Property(t => t.LoginID);
          this.Property(t => t.LoginName).HasMaxLength(50);
          this.Property(t => t.Password).HasMaxLength(40);
          this.Property(t => t.UserRealName).HasMaxLength(100);
          this.Property(t => t.UserSex).HasMaxLength(10);
          this.Property(t => t.UserIDCardNumber).HasMaxLength(50);
          this.Property(t => t.UserEmail).HasMaxLength(100);
          this.Property(t => t.UserTel).HasMaxLength(50);
          this.Property(t => t.UserMobile).HasMaxLength(50);
          this.Property(t => t.UserAddress).HasMaxLength(255);
          this.Property(t => t.UserZipcode).HasMaxLength(50);
          this.Property(t => t.UserRegTime);
          this.Property(t => t.UserEndTime);
          this.Property(t => t.UserVerify).HasMaxLength(20);
          this.Property(t => t.UserFeeType).HasMaxLength(50);
          this.Property(t => t.UserType).HasMaxLength(50);
          this.Property(t => t.UserState).HasMaxLength(50);
          this.Property(t => t.UserCity).HasMaxLength(50);
          this.Property(t => t.OrgName).HasMaxLength(255);
          this.Property(t => t.OrgUnitName).HasMaxLength(255);
          this.Property(t => t.UserFax).HasMaxLength(50);
          this.Property(t => t.Certi_id).HasMaxLength(50);
          this.Property(t => t.DealMan).HasMaxLength(50);
          this.Property(t => t.DealmanTel).HasMaxLength(50);
          this.Property(t => t.UserLoginType).HasMaxLength(50);
          this.Property(t => t.UserSignPic).HasMaxLength(100);
          this.Property(t => t.Status_CA);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
