//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Domain
{
    
    public partial class Accounts_Users : BaseEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TrueName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<bool> Activity { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Style { get; set; }
    		public virtual Hotel UserHotel { get; set; }
    		}
}
