//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Domain
{
    
    public partial class Book_Rdetail : BaseEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string Book_no { get; set; }
        public int Real_type_Id { get; set; }
        public string Room_number { get; set; }
        public Nullable<int> Real_num { get; set; }
        public Nullable<decimal> Book_Price { get; set; }
        public Nullable<decimal> Real_Price { get; set; }
        public Nullable<int> Real_Scheme_Id { get; set; }
        public Nullable<int> Ok_num { get; set; }
        public Nullable<int> Room_typeid { get; set; }
    		public virtual Hotel UserHotel { get; set; }
    		
        public virtual book_room book_room { get; set; }
    }
}
