//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Domain
{
    
    public partial class book_room : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book_room()
        {
            this.Book_Rdetail = new HashSet<Book_Rdetail>();
        }
    
        
        public Nullable<int> hotelid { get; set; }
        public string book_no { get; set; }
        public string book_Name { get; set; }
        public string tele_no { get; set; }
        public string onli_no { get; set; }
        public string guar_way { get; set; }
        public string mem_cardno { get; set; }
        public Nullable<System.DateTime> time_to { get; set; }
        public Nullable<System.DateTime> time_from { get; set; }
        public Nullable<System.DateTime> real_time { get; set; }
        public Nullable<int> source_id { get; set; }
        public Nullable<int> meth_pay_id { get; set; }
        public Nullable<decimal> deposit { get; set; }
        public Nullable<int> real_type_id { get; set; }
        public Nullable<int> real_scheme_id { get; set; }
        public Nullable<decimal> real_price { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> real_num { get; set; }
        public string remark { get; set; }
        public string room_number { get; set; }
        public Nullable<decimal> back_deposit { get; set; }
        public string userid { get; set; }
        public string Accounts { get; set; }
        public Nullable<int> CpID { get; set; }
    		public virtual Hotel UserHotel { get; set; }
    		
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Rdetail> Book_Rdetail { get; set; }
    }
}
