//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using HoteManagement.Caching;
using HoteManagement.Data;
using HoteManagement.Data.Dapper.UnitOfWork;
using HoteManagement.Infrastructure.Domain;
using HoteManagement.Service.Events;
using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    public abstract class ApplicationService : IApplicationService
    {
      
        protected readonly IRepository<Domain.UserInfo> _UserInfoRepository;
        protected readonly ILogger _logger;
        protected IDbConnectionProvider _dbConnectionProvider;

        public ApplicationService(

          IRepository<Domain.UserInfo> UserInfoRepository,
          IDbConnectionProvider dbConnectionProvider,
          ILogger logger)
        {

            _UserInfoRepository = UserInfoRepository;
            _dbConnectionProvider = dbConnectionProvider;
            _logger = logger;

        }

}

}
