//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Data.Mapping
{
    
    
    public class HotelMap : BaseEntityTypeConfiguration<HoteManagement.Domain.Hotel>
    {
       public HotelMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.HotelName).HasMaxLength(64);
          this.Property(t => t.IsChain);
          this.Property(t => t.IsTop);
          this.Property(t => t.ParentId);
          this.Property(t => t.IsDeleted);
          this.Property(t => t.Expiretime);
          this.Property(t => t.Registertime);
          this.Property(t => t.CreateorId);
          this.Property(t => t.CreateorIp).HasMaxLength(32);
          this.Property(t => t.Createtime);
          this.Property(t => t.Updatetime);

       }
    }
}
