//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Data.Mapping
{
    
    
    public class paymentMoneyMap : BaseEntityTypeConfiguration<HoteManagement.Domain.paymentMoney>
    {
       public paymentMoneyMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.orderno).HasMaxLength(50);
          this.Property(t => t.pm_Money);
          this.Property(t => t.pm_MethPayid);
          this.Property(t => t.pm_Name).HasMaxLength(50);
          this.Property(t => t.pm_roomNumber).HasMaxLength(50);
          this.Property(t => t.pm_Date);
          this.Property(t => t.pm_Remaker);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
