//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Data.Mapping
{
    
    
    public class room_typeMap : BaseEntityTypeConfiguration<HoteManagement.Domain.room_type>
    {
       public room_typeMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.room_number).HasMaxLength(50);
          this.Property(t => t.room_name).HasMaxLength(50);
          this.Property(t => t.room_hour).HasMaxLength(50);
          this.Property(t => t.room_listedmoney);
          this.Property(t => t.room_zmmoney);
          this.Property(t => t.room_hourmation).HasMaxLength(200);
          this.Property(t => t.room_reamker).HasMaxLength(200);
          this.Property(t => t.room_image);
          this.Property(t => t.room_ealry_price);
          this.Property(t => t.room_Moth_price);
          this.Property(t => t.room_Bfb);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
