//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Data.Mapping
{
    
    
    public class room_numberMap : BaseEntityTypeConfiguration<HoteManagement.Domain.room_number>
    {
       public room_numberMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.hotelid);
          this.Property(t => t.Rn_flloeld).HasMaxLength(50);
          this.Property(t => t.Rn_floor).HasMaxLength(50);
          this.Property(t => t.Rn_roomNum).HasMaxLength(20);
          this.Property(t => t.Rn_state);
          this.Property(t => t.Rn_room);
          this.Property(t => t.Rn_Type);
          this.Property(t => t.Rn_price);
          this.Property(t => t.Rn_remaker);
          this.Property(t => t.Room_suod).HasMaxLength(10);
          this.Property(t => t.Room_sort);
          this.Property(t => t.Rn_Tobe);
          this.Property(t => t.Rn_suo).HasMaxLength(50);
          this.HasRequired(t => t.UserHotel).WithMany().HasForeignKey(t => t.hotelid);
       }
    }
}
