//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    
    public partial class cost_typeDto : BaseDtoEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string ct_number { get; set; }
        public string ct_name { get; set; }
        public Nullable<int> ct_iftype { get; set; }
        public string ct_remark { get; set; }
        public Nullable<decimal> ct_money { get; set; }
        public Nullable<int> ct_categories { get; set; }
    		public virtual HotelDto UserHotel { get; set; }

        public virtual cost_typeDto cost_typecategory { get; set; }
    		}
}
