//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    
    public partial class cprotocolPriceDto : BaseDtoEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string Accounts { get; set; }
        public Nullable<int> RoomType { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> protoPrice { get; set; }
        public Nullable<int> mothPrice { get; set; }
        public Nullable<double> zdPrice { get; set; }
        public Nullable<int> lcPrice { get; set; }
        public Nullable<int> Breakfast { get; set; }
        public Nullable<int> commission { get; set; }
        public Nullable<int> cpID { get; set; }
    		public virtual HotelDto UserHotel { get; set; }
    		}
}
