//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    
    public partial class cprotocolDto : BaseDtoEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string Accounts { get; set; }
        public string Ptheme { get; set; }
        public Nullable<int> pType { get; set; }
        public string PNumber { get; set; }
        public Nullable<bool> ishire { get; set; }
        public Nullable<System.DateTime> term { get; set; }
        public Nullable<System.DateTime> period { get; set; }
        public Nullable<int> breakfast { get; set; }
        public Nullable<int> Commission { get; set; }
        public Nullable<bool> Dayhire { get; set; }
        public Nullable<bool> prohire { get; set; }
        public string signatory { get; set; }
        public string companysignatory { get; set; }
        public string roomNumber { get; set; }
        public Nullable<bool> Isdiscount { get; set; }
        public Nullable<double> discount { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> isVerify { get; set; }
        public string editUser { get; set; }
        public Nullable<int> verifyUser { get; set; }
        public string Details { get; set; }
    		public virtual HotelDto UserHotel { get; set; }
    		}
}
