//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{

    public partial class MenuDto : BaseDtoEntity
    {

        public Nullable<int> hotelid { get; set; }
        public string title { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string url { get; set; }
        public string imgurl { get; set; }
        public Nullable<int> sortId { get; set; }
        public Nullable<bool> isable { get; set; }
        public virtual HotelDto UserHotel { get; set; }
        public virtual MenuDto ParentMenu { get; set; }

        public virtual List<MenuDto> ChildMenus { get; set; }
    }

    public class Menu
    {

        public Menu()
        {
            ClildMenus = new List<MenuDto>();
        }

        public MenuDto ParentMenu { get; set; }
        public List<MenuDto> ClildMenus { get; set; }
    }


    public class UserMenus
    {

        public UserMenus()
        {
            Menus = new List<Menu>();
        }

        public int UserId { get; set; }
        public int RoleId { get; set; }

        public List<Menu> Menus { get; set; }
    }
}
