//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    
    public partial class order_inforDto : BaseDtoEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string order_no { get; set; }
        public string room_id { get; set; }
        public Nullable<int> occ_id { get; set; }
        public Nullable<decimal> order_money { get; set; }
        public Nullable<decimal> return_money { get; set; }
        public string order_state { get; set; }
        public Nullable<System.DateTime> order_time { get; set; }
        public string remark { get; set; }
    		public virtual HotelDto UserHotel { get; set; }
    		}
}
