//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    
    public partial class UsersDto : BaseDtoEntity
    {
        
        public Nullable<int> hotelid { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string passwords { get; set; }
        public Nullable<int> user_type { get; set; }
        public Nullable<System.DateTime> pubdate { get; set; }
    		public virtual HotelDto UserHotel { get; set; }
    		}
}
